apiVersion: apps/v1
kind: Deployment
metadata:
  name: ateccoin
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ateccoin
  template:
    metadata:
      labels:
        app: ateccoin
        version: v0.15
    spec:
      containers:
      - name: ateccoin
        image: toolboc/ateccoin
        ports:
        - containerPort: 9495
          name: ateccoin
          protocol: TCP